# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
# SGX: algonaut 0.3.0+ requires Rust 1.51, for min_const_generics:
# https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1510-2021-03-25
channel = "nightly-2021-03-25"
